# Generated by Django 4.2.4 on 2025-03-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_option_optiongroup_product_productattribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(blank=True, to='catalog.option'),
        ),
    ]
