# Generated by Django 4.2.4 on 2025-03-26 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_productitem_options_productitem_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optiongroupvalue',
            options={'verbose_name': 'Option Group Value', 'verbose_name_plural': 'Option Group Values'},
        ),
        migrations.AlterModelOptions(
            name='productitem',
            options={'verbose_name': 'Product Item', 'verbose_name_plural': 'Product Items'},
        ),
        migrations.RemoveField(
            model_name='option',
            name='option_group',
        ),
        migrations.RemoveField(
            model_name='product',
            name='options',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='product_class',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='recommended_product',
        ),
        migrations.AddField(
            model_name='optiongroup',
            name='options',
            field=models.ManyToManyField(related_name='groups', to='catalog.option'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='options',
            field=models.ManyToManyField(blank=True, to='catalog.option'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='recommended_products',
            field=models.ManyToManyField(blank=True, to='catalog.productitem'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_multi_option',
            field=models.ManyToManyField(blank=True, to='catalog.optiongroupvalue'),
        ),
        migrations.DeleteModel(
            name='ProductRecommendation',
        ),
    ]
