# Generated by Django 4.2.4 on 2025-03-26 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_category_slug_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optiongroupvalue',
            options={'verbose_name': 'Option Group value', 'verbose_name_plural': 'Option Group values'},
        ),
        migrations.AlterModelOptions(
            name='productitem',
            options={'verbose_name': 'ProductItem', 'verbose_name_plural': 'Product Items'},
        ),
        migrations.RemoveField(
            model_name='optiongroup',
            name='options',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='options',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='recommended_products',
        ),
        migrations.AddField(
            model_name='option',
            name='option_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.optiongroup'),
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(blank=True, to='catalog.option'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes_related', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='product_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=True),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_multi_option',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.optiongroupvalue'),
        ),
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_recommendation', to='catalog.productitem')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productitem')),
            ],
            options={
                'ordering': ('primary', '-rank'),
                'unique_together': {('primary', 'recommendation')},
            },
        ),
        migrations.AddField(
            model_name='productitem',
            name='recommended_product',
            field=models.ManyToManyField(blank=True, through='catalog.ProductRecommendation', to='catalog.productitem'),
        ),
    ]
