# Generated by Django 4.2.4 on 2025-03-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_category_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductClass',
        ),
        migrations.AlterModelOptions(
            name='productattributevalue',
            options={'verbose_name': 'Product Attribute Value', 'verbose_name_plural': 'Product Attribute Values'},
        ),
    ]
