# Generated by Django 4.2.4 on 2025-03-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_rename_product_productclass_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productclass',
            options={'verbose_name': 'Product class', 'verbose_name_plural': 'Product classes'},
        ),
        migrations.RemoveField(
            model_name='productclass',
            name='options',
        ),
    ]
