# Generated by Django 4.2.4 on 2025-03-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_productclass_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productclass',
            name='options',
        ),
        migrations.AddField(
            model_name='productitem',
            name='options',
            field=models.ManyToManyField(blank=True, to='catalog.option'),
        ),
    ]
