# Generated by Django 4.2.4 on 2025-03-27 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_color_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.color')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.productitem')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.size')),
            ],
        ),
        migrations.AddConstraint(
            model_name='productitemvariant',
            constraint=models.UniqueConstraint(fields=('product_item', 'color', 'size'), name='unique_variant'),
        ),
        migrations.AddConstraint(
            model_name='productitemvariant',
            constraint=models.CheckConstraint(check=models.Q(('color__isnull', False), ('size__isnull', False), _connector='OR'), name='at_least_one_attribute'),
        ),
    ]
