# Generated by Django 4.2.4 on 2025-03-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_productitemvariant_productitemvariant_unique_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevalue',
            name='price',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
