# Generated by Django 4.2.4 on 2025-03-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_productattributevalue_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitemvariant',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
