# Generated by Django 4.2.4 on 2025-03-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_productitemvariant_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitemvariant',
            name='price',
        ),
    ]
