# Generated by Django 4.2.4 on 2025-03-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_remove_productitemvariant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitemvariant',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
