# Generated by Django 4.2.4 on 2025-03-28 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_remove_productattributevalue_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributevalue',
            name='value_multi_option',
        ),
    ]
