# Generated by Django 4.2.4 on 2025-03-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_remove_productattributevalue_value_multi_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
