# Generated by Django 4.2.4 on 2025-03-28 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_productitem_option_groups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAttribute',
            new_name='ProductClassAttribute',
        ),
    ]
