# Generated by Django 4.2.4 on 2025-03-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_rename_productattribute_productclassattribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productclassattribute',
            options={'verbose_name': 'Product class Attribute', 'verbose_name_plural': 'Product class Attributes'},
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='stock',
        ),
    ]
