# Generated by Django 4.2.4 on 2025-03-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_alter_productclassattribute_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productitemvariant',
            name='at_least_one_attribute',
        ),
    ]
