# Generated by Django 4.2.4 on 2025-03-28 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_alter_productitemvariant_color_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productitemvariant',
            name='unique_variant',
        ),
        migrations.RemoveField(
            model_name='productitemvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productitemvariant',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productitemvariant',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productitemvariant',
            name='stock',
        ),
    ]
