# Generated by Django 4.2.4 on 2025-03-28 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_remove_productitemvariant_unique_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitemvariant',
            name='color',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.color'),
        ),
        migrations.AddField(
            model_name='productitemvariant',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productitemvariant',
            name='size',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.size'),
        ),
        migrations.AddField(
            model_name='productitemvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='productitemvariant',
            constraint=models.UniqueConstraint(fields=('product_item', 'color', 'size'), name='unique_variant'),
        ),
    ]
