# Generated by Django 4.2.4 on 2025-03-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_alter_productitemvariant_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevalue',
            name='value_boolean',
            field=models.BooleanField(default=False),
        ),
    ]
