# Generated by Django 4.2.4 on 2025-03-29 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_productattributevalue_value_boolean'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='categories_product_class', to='catalog.category'),
            preserve_default=False,
        ),
    ]
