# Generated by Django 4.2.4 on 2025-03-29 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_productclass_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productclass',
            name='category',
        ),
    ]
