# Generated by Django 4.2.4 on 2025-03-29 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_remove_productclass_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories_product_class', to='catalog.category'),
        ),
    ]
