# Generated by Django 4.2.4 on 2025-03-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0046_alter_productitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='option_groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='option_groups', to='catalog.optiongroup'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='options',
            field=models.ManyToManyField(blank=True, null=True, related_name='options', to='catalog.optiongroupvalue'),
        ),
    ]
